import { MigrationInterface, QueryRunner } from "typeorm";

export class MandaiTypeORM1750645053557 implements MigrationInterface {
    name = 'MandaiTypeORM1750645053557'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`ACCESS_MATRIX_PERMISSIONS\` (\`PERMISSION_ID\` int NOT NULL AUTO_INCREMENT, \`PERMISSION_NAME\` varchar(100) NOT NULL, \`DESCRIPTION\` text NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_1b9e9f9a70d208bdcedda814bc\` (\`PERMISSION_NAME\`), PRIMARY KEY (\`PERMISSION_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ACCESS_MATRIX_ROLE_PERMS\` (\`ROLE_PERMISSION_ID\` int NOT NULL AUTO_INCREMENT, \`ROLE_ID\` int NOT NULL, \`PERMISSION_ID\` int NOT NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`ROLE_PERMISSION_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ACCESS_MATRIX_ROLES\` (\`ROLE_ID\` int NOT NULL AUTO_INCREMENT, \`ROLE_NAME\` varchar(100) NOT NULL, \`DESCRIPTION\` text NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_6a567c54becc9f8084cff96531\` (\`ROLE_NAME\`), PRIMARY KEY (\`ROLE_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ACCESS_MATRIX_USR_ROLES\` (\`USER_ROLE_ID\` int NOT NULL AUTO_INCREMENT, \`ACCESS_ID\` int NOT NULL, \`ROLE_ID\` int NOT NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`USER_ROLE_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`TASKS\` (\`TASK_ID\` int NOT NULL AUTO_INCREMENT, \`TITLE\` varchar(255) NOT NULL, \`DESCRIPTION\` text NULL, \`STATUS\` enum ('pending', 'in-progress', 'completed', 'blocked') NOT NULL DEFAULT 'pending', \`CREATED_BY\` int NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`IS_DELETED\` tinyint NOT NULL DEFAULT '0', \`DELETED_AT\` timestamp NULL, PRIMARY KEY (\`TASK_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ACCESS_MATRIX\` (\`ACCESS_ID\` int NOT NULL AUTO_INCREMENT, \`USERNAME\` varchar(255) NOT NULL, \`PW_HASH\` varchar(255) NOT NULL, \`EMAIL\` varchar(255) NULL, \`UPDATED_AT\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_254f2af384298f18ca7ce39d59\` (\`USERNAME\`), UNIQUE INDEX \`IDX_7f418de0cbdf61271d542550eb\` (\`EMAIL\`), PRIMARY KEY (\`ACCESS_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_ROLE_PERMS\` ADD CONSTRAINT \`FK_612d6864f84365286c1f9d1ad8c\` FOREIGN KEY (\`ROLE_ID\`) REFERENCES \`ACCESS_MATRIX_ROLES\`(\`ROLE_ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_ROLE_PERMS\` ADD CONSTRAINT \`FK_725405c1397e4d6ee42d3577821\` FOREIGN KEY (\`PERMISSION_ID\`) REFERENCES \`ACCESS_MATRIX_PERMISSIONS\`(\`PERMISSION_ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_USR_ROLES\` ADD CONSTRAINT \`FK_4fbcf44c8b11b38e820fa0fdecf\` FOREIGN KEY (\`ACCESS_ID\`) REFERENCES \`ACCESS_MATRIX\`(\`ACCESS_ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_USR_ROLES\` ADD CONSTRAINT \`FK_17b0f1ce3a4452ff36440c5c096\` FOREIGN KEY (\`ROLE_ID\`) REFERENCES \`ACCESS_MATRIX_ROLES\`(\`ROLE_ID\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`TASKS\` ADD CONSTRAINT \`FK_2d9acdce11806edc6617e3e1e7f\` FOREIGN KEY (\`CREATED_BY\`) REFERENCES \`ACCESS_MATRIX\`(\`ACCESS_ID\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`TASKS\` DROP FOREIGN KEY \`FK_2d9acdce11806edc6617e3e1e7f\``);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_USR_ROLES\` DROP FOREIGN KEY \`FK_17b0f1ce3a4452ff36440c5c096\``);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_USR_ROLES\` DROP FOREIGN KEY \`FK_4fbcf44c8b11b38e820fa0fdecf\``);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_ROLE_PERMS\` DROP FOREIGN KEY \`FK_725405c1397e4d6ee42d3577821\``);
        await queryRunner.query(`ALTER TABLE \`ACCESS_MATRIX_ROLE_PERMS\` DROP FOREIGN KEY \`FK_612d6864f84365286c1f9d1ad8c\``);
        await queryRunner.query(`DROP INDEX \`IDX_7f418de0cbdf61271d542550eb\` ON \`ACCESS_MATRIX\``);
        await queryRunner.query(`DROP INDEX \`IDX_254f2af384298f18ca7ce39d59\` ON \`ACCESS_MATRIX\``);
        await queryRunner.query(`DROP TABLE \`ACCESS_MATRIX\``);
        await queryRunner.query(`DROP TABLE \`TASKS\``);
        await queryRunner.query(`DROP TABLE \`ACCESS_MATRIX_USR_ROLES\``);
        await queryRunner.query(`DROP INDEX \`IDX_6a567c54becc9f8084cff96531\` ON \`ACCESS_MATRIX_ROLES\``);
        await queryRunner.query(`DROP TABLE \`ACCESS_MATRIX_ROLES\``);
        await queryRunner.query(`DROP TABLE \`ACCESS_MATRIX_ROLE_PERMS\``);
        await queryRunner.query(`DROP INDEX \`IDX_1b9e9f9a70d208bdcedda814bc\` ON \`ACCESS_MATRIX_PERMISSIONS\``);
        await queryRunner.query(`DROP TABLE \`ACCESS_MATRIX_PERMISSIONS\``);
    }

}
